# Generated by Django 4.2.2 on 2023-06-16 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HairProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_type', models.CharField(choices=[('1a', '1a'), ('1b', '1b'), ('1c', '1c'), ('2a', '2a'), ('2b', '2b'), ('2c', '2c'), ('3a', '3a'), ('3b', '3b'), ('3c', '3c'), ('4a', '4a'), ('4b', '4b'), ('4c', '4c')], default='4c', max_length=2)),
                ('hair_porosity', models.CharField(choices=[('low', 'Low Porosity'), ('medium', 'Medium Porosity'), ('high', 'Hight Porosity')], default='low', max_length=6)),
                ('hair_condition', models.CharField(choices=[('protein_overload', 'Protein Overload'), ('moisture_overload', 'Moisture Overload'), ('healthy', 'Healthy'), ('dandruff', 'Dandruff'), ('hair_loss', 'Hair Loss'), ('dry_hair', 'Dry Hair'), ('split_ends', 'Split Ends'), ('greasy', 'Greasy Hair'), ('frizzy', 'Frizzy'), ('heat_damage', 'Heat Damage'), ('color_damage', 'Color Damage')], default='protein_overload', max_length=20)),
                ('hair_length', models.CharField(choices=[('ear', 'Ear Length'), ('necktop', 'Neck (top) Length'), ('neckbottom', 'Neck (bottom) Length'), ('collarbone', 'Collarbone Length'), ('shoulder', 'Shoulder Length'), ('armpit', 'Armpit Length'), ('brastrap', 'Bra Strap Length'), ('midback', 'Mid Back Length'), ('waist', 'Waist Length'), ('hip', 'Hip Length'), ('tailbone', 'Tailbone Length'), ('classic', 'Classic Length'), ('midthigh', 'Mid Thigh Length'), ('knee', 'Knee Length'), ('calf', 'Calf Length'), ('ankle', 'Ankle Length'), ('floor', 'Floor Length')], default='ear', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
