# Generated by Django 4.2.2 on 2023-11-22 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_hairproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hair_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.hairroutine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.hairproduct')),
            ],
        ),
    ]
