# Generated by Django 4.2.2 on 2023-11-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairroutine',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hairroutine',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
