# Generated by Django 4.2.2 on 2023-11-24 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routines', '0004_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routines.comment'),
        ),
        migrations.AddField(
            model_name='hairroutine',
            name='likes',
            field=models.ManyToManyField(related_name='liked_routines', through='routines.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
